refactor: typescrip 5.6.3에서 5.4.4로 다운그레이

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,16 +3,15 @@
 echo "🪄Running ESLint..."
 yarn run lint
 
-exit 1
+if [ $? -ne 0 ]; then
+    echo "❌ Linting failed. Commit aborted."
+    exit 1  # 린트에 실패하면 커밋을 중단합니다.
+fi
 
 current_branch=$(git branch --show-current)
 
 restricted_branches="^(main|master|dev)$"
 
-if [ $? -ne 0 ]; then
-    echo "❌ Linting failed. Commit aborted."
-    exit 1  # 린트에 실패하면 커밋을 중단합니다.
-fi
 
 if [[ $current_branch =~ $restricted_branches ]]; then
   echo "❌ You are on a restricted branch: $current_branch.. ❌"
